#!/bin/sh

script_name="install.py"
dir_path=$(dirname "$0")

TEXT_BOLD='\033[1m'
TEXT_INVERTED='\033[7m'
NC='\033[0m' # No Color


echo "
============================================================
🚀 ${TEXT_BOLD}Рокетбанк ${NC} для macOS
============================================================
\n
Сейчас мы проверим и установим (если еще нету) нужное ПО (brew, python3, pip)
Возможно Вас попросят ввести пароль от компьютера (это необходимо для установки ПО)
Если что-то пошло не так, нажимайте Command + Q
\n\n"


chmod +x "$dir_path/../rocketbank.5m.py"
[ -f "$dir_path/../README.md" ] && rm "$dir_path/../README.md"
[ -f "$dir_path/../LICENSE" ] && rm "$dir_path/../LICENSE"
[ -f "$dir_path/../.gitignore" ] && rm "$dir_path/../.gitignore"
[ -f "$dir_path/../LATEST_BUILD.json" ] && rm "$dir_path/../LATEST_BUILD.json"

if ! [[ $(which -a python3) ]]; then
    echo "Пару минут, пожалуйста!"
    if ! [[ $(which -a brew) ]]; then
        yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" &>/dev/null
        yes | brew doctor &>/dev/null
    fi
    yes | brew install python3 &>/dev/null
fi
if ! [[ $(which -a pip) ]]; then
    python3 get-pip.py
fi
yes | pip3 install requests --quiet
touch "$dir_path/my.cfg"

echo "\nГотово! Давайте знакомиться :)\n"

python3 "$dir_path/$script_name"